name: Documentation CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Generate Changelog
        if: github.actor != 'github-actions[bot]'
        run: |
          rm -f index.md
          npm install -g conventional-changelog-cli
          conventional-changelog -i index.md -s --config ./changelog-config.js
          git add index.md
          git commit -m "chore: update changelog"
          git push origin main

      - run: dotnet tool update -g docfx
      - run: docfx docfx.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site